In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn import metrics
import statsmodels.api as sm
from sklearn.preprocessing import LabelEncoder

mortgages = pd.read_csv('/Users/pleiades/Downloads/dataMiningPbl/data.csv')
mortgages.head()

,Bo_Age,Ln_Orig,Orig_LTV_Ratio_Pct,Credit_score,First_home,Tot_mthly_debt_exp,Tot_mthly_incm,orig_apprd_val_amt,pur_prc_amt,DTI Ratio,Status,OUTCOME,State,Median_state_inc,UPB>Appraisal
0,37,75650.0,85,669,N,1707,6000,169000,160000,0.284500,Active,non-default,FL,"40,171",0
1,46,390775.0,102,684,N,0,5025,310000,309000,0.000000,Pay-off,non-default,NY,"44,228",1
2,30,112500.0,90,662,Y,1812,4800,177000,176450,0.377500,Pay-off,non-default,CA,"49,894",0
3,24,85250.0,97,647,N,3395,6934,113000,110000,0.489616,Pay-off,non-default,GA,"43,217",0
4,35,114000.0,100,791,N,3801,5504,103000,103000,0.690589,Pay-off,non-default,NH,"57,352",1

매달 상환 금액이 0 인데 상태는 지불완료인 행

In [17]:
mortgages[(mortgages['Tot_mthly_debt_exp'] == 0) & (mortgages['Status'] == 'Pay-off')]

,Bo_Age,Ln_Orig,Orig_LTV_Ratio_Pct,Credit_score,First_home,Tot_mthly_debt_exp,Tot_mthly_incm,orig_apprd_val_amt,pur_prc_amt,DTI Ratio,Status,OUTCOME,State,Median_state_inc,UPB>Appraisal
1,46,390775.0,102,684,N,0,5025,310000,309000,0.0,Pay-off,non-default,NY,"44,228",1
50,25,156000.0,100,631,N,0,6424,270000,265990,0.0,Pay-off,non-default,CA,"49,894",0
80,39,63400.0,100,665,Y,0,6375,313000,330000,0.0,Pay-off,non-default,CA,"49,894",0
130,34,301950.0,85,698,N,0,5025,223000,200000,0.0,Pay-off,non-default,NJ,"56,772",1
171,40,186400.0,90,702,N,0,5025,195000,194000,0.0,Pay-off,non-default,FL,"40,171",0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10288,29,144900.0,100,634,Y,0,5194,255000,254410,0.0,Pay-off,non-default,NY,"44,228",0
10289,43,205000.0,100,569,Y,0,5025,90000,89900,0.0,Pay-off,non-default,LA,"35,523",1
10363,34,110000.0,100,771,N,0,4590,182000,179000,0.0,Pay-off,non-default,NJ,"56,772",0
10366,57,322700.0,90,651,N,0,5025,154000,152312,0.0,Pay-off,non-default,FL,"40,171",1
10419,34,273000.0,100,760,Y,0,5025,435000,435000,0.0,Pay-off,non-default,NJ,"56,772",0

In [29]:
x = mortgages.loc[: ,'Ln_Orig':'UPB>Appraisal']
y = mortgages['OUTCOME']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)
print(len(x_train))
print(len(x_test))
print(len(y_train))
print(len(y_test))

7955
2652
7955
2652

In [40]:
log_reg = LogisticRegression()
log_reg.fit(x_train, y_train)
 
y_pred = log_reg.predict(x_test)
print(y_pred)
print(list(y_test)) 
print('정확도 :', metrics.accuracy_score(y_test, y_pred))

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

ValueError: could not convert string to float: '45,787'